
export const Images={
    starImage:{
        Link:"/image/star.svg",
        alt:"star",
    },
    unionImage:{
        Link:"/image/union.svg"
    },
    download:{
        Link:"/image"
    },
    success:{
        Link:'/image/success.svg'
    },
    download:{
        Link:'/image/download.svg'
    },
    small:{
        Link:'/image/small.svg'
    },
    paper:{
        Link:'/image/paper.svg'
    },
    downloadButton:{
        Link:'/image/downloadButton.svg'
    },
    ss:{
        Link:'/image/ss.svg'
    },
    eclips:{
        Link:'/image/elipse.svg'
    },
    lock:{
        Link:'/image/Lock.svg'
    },
    line:{
        Link:'/image/line.svg'
    },
    cart:{
        Link:'/image/Cart.svg'
    },
    phone:{
        Link:'/image/Phone.svg'
    },
    avatar:{
        Link:'/image/Avatar.svg'
    },
    logo:{
        Link:'/image/logo.svg'
    },
    pi:{
        Link:'/image/pi.svg'
    },
    linkedin:{
        Link:'/image/linkedin.svg'
    },
    facebook:{
        Link:'/image/facebook.svg'
    },
    ig:{
        Link:'/image/ig.svg'
    },
    twitter:{
        Link:'/image/twitter.svg'
    },
    dropdown:{
        Link:'/image/dropdown.svg'
    },
    next:{
        Link:'/image/Next.svg'
    },
    previous:{
        Link:'/image/Previous.svg'
    },
    tick:{
        Link:'/image/Tick.svg'
    },
    list:{
        Link:"/image/list.svg"
    },
    eye:{
        Link:'/image/eye.svg'
    },
    flash:{
        Link:'/image/flash.png'
    },
    tatlor:{
        Link:'/image/tatler.png'
    },
    statlor:{
        Link:'/image/stetlor.png'
    },
    group:{
        Link:'/image/group.svg'
    },
    half:{
        Link:'/image/half.svg'
    },
    right:{
        Link:'/image/right.svg'
    }
}